### ISSUE TITLE
[ERROR] script/alert-overdue-requests (ActionView::Template::Error) "missing interpolation argument"

### ISSUE THREAD

**Issue by garethrees** [mysociety/greece-theme#3]
```
/data/vhost/greece.alaveteli.org/alaveteli-2021-04-09T17-48-42/lib/i18n_fixes.rb:35:in `block in gettext_interpolate': missing interpolation argument "public_body_name" in {:public_body=>"Test authority"} ("Κάντε κλικ στο λινκ παρακάτς για να στείλετε ένα μήνυμα στο {{public_body_name}} υπενθυμίζοντάς τους να απαντήσουν στην αίτησή σας. " given) (ActionView::Template::Error)
from /data/vhost/greece.alaveteli.org/alaveteli-2021-04-09T17-48-42/lib/i18n_fixes.rb:31:in `gsub'
from /data/vhost/greece.alaveteli.org/alaveteli-2021-04-09T17-48-42/lib/i18n_fixes.rb:31:in `gettext_interpolate'
from /data/vhost/greece.alaveteli.org/alaveteli-2021-04-09T17-48-42/lib/i18n_fixes.rb:11:in `_'
from /data/vhost/greece.alaveteli.org/alaveteli-2021-04-09T17-48-42/app/views/request_mailer/overdue_alert.text.erb:8:in `_app_views_request_mailer_overdue_alert_text_erb___2418634210342364267_47317116041760'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/template.rb:159:in `block in render'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/notifications.rb:170:in `instrument'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/template.rb:354:in `instrument_render_template'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/template.rb:157:in `render'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/notifications.rb:168:in `block in instrument'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/notifications.rb:168:in `instrument'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/renderer/template_renderer.rb:16:in `render'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/renderer/renderer.rb:44:in `render_template'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/renderer/renderer.rb:25:in `render'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/rendering.rb:103:in `_render_template'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/rendering.rb:84:in `render_to_body'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/abstract_controller/rendering.rb:25:in `render'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/base.rb:943:in `block in collect_responses_from_templates'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/base.rb:940:in `each'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/base.rb:940:in `each'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/base.rb:940:in `map'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/base.rb:940:in `collect_responses_from_templates'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/base.rb:925:in `collect_responses'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/base.rb:828:in `mail'
from /data/vhost/greece.alaveteli.org/alaveteli-2021-04-09T17-48-42/app/mailers/application_mailer.rb:31:in `mail_user'
from /data/vhost/greece.alaveteli.org/alaveteli-2021-04-09T17-48-42/app/mailers/request_mailer.rb:112:in `overdue_alert'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/abstract_controller/base.rb:194:in `process_action'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:132:in `run_callbacks'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/abstract_controller/callbacks.rb:41:in `process_action'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/abstract_controller/base.rb:134:in `process'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/rescuable.rb:25:in `block in process'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/rescuable.rb:24:in `process'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/rendering.rb:32:in `process'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/base.rb:607:in `block in process'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/notifications.rb:168:in `block in instrument'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/notifications.rb:168:in `instrument'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/base.rb:606:in `process'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/message_delivery.rb:123:in `block in processed_mailer'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/message_delivery.rb:122:in `tap'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/message_delivery.rb:122:in `processed_mailer'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/message_delivery.rb:113:in `deliver_now'
from /data/vhost/greece.alaveteli.org/alaveteli-2021-04-09T17-48-42/app/mailers/request_mailer.rb:327:in `block in alert_overdue_requests'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.5/lib/active_record/relation/delegation.rb:71:in `each'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.5/lib/active_record/relation/delegation.rb:71:in `each'
from /data/vhost/greece.alaveteli.org/alaveteli-2021-04-09T17-48-42/app/mailers/request_mailer.rb:288:in `alert_overdue_requests'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/commands/runner/runner_command.rb:41:in `<main>'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/commands/runner/runner_command.rb:41:in `eval'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/commands/runner/runner_command.rb:41:in `perform'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/command/base.rb:69:in `perform'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/command.rb:46:in `invoke'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/commands.rb:18:in `<top (required)>'
from bin/rails:4:in `require'
from bin/rails:4:in `<main>'
/data/vhost/greece.alaveteli.org/alaveteli-2021-04-09T17-48-42/lib/i18n_fixes.rb:35:in `block in gettext_interpolate': missing interpolation argument "public_body_name" in {:public_body=>"Test authority"} ("Κάντε κλικ στο λινκ παρακάτς για να στείλετε ένα μήνυμα στο {{public_body_name}} υπενθυμίζοντάς τους να απαντήσουν στην αίτησή σας. " given) (I18n::MissingInterpolationArgument)
from /data/vhost/greece.alaveteli.org/alaveteli-2021-04-09T17-48-42/lib/i18n_fixes.rb:31:in `gsub'
from /data/vhost/greece.alaveteli.org/alaveteli-2021-04-09T17-48-42/lib/i18n_fixes.rb:31:in `gettext_interpolate'
from /data/vhost/greece.alaveteli.org/alaveteli-2021-04-09T17-48-42/lib/i18n_fixes.rb:11:in `_'
from /data/vhost/greece.alaveteli.org/alaveteli-2021-04-09T17-48-42/app/views/request_mailer/overdue_alert.text.erb:8:in `_app_views_request_mailer_overdue_alert_text_erb___2418634210342364267_47317116041760'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/template.rb:159:in `block in render'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/notifications.rb:170:in `instrument'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/template.rb:354:in `instrument_render_template'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/template.rb:157:in `render'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/notifications.rb:168:in `block in instrument'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/notifications.rb:168:in `instrument'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/renderer/template_renderer.rb:16:in `render'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/renderer/renderer.rb:44:in `render_template'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/renderer/renderer.rb:25:in `render'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/rendering.rb:103:in `_render_template'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/rendering.rb:84:in `render_to_body'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/abstract_controller/rendering.rb:25:in `render'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/base.rb:943:in `block in collect_responses_from_templates'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/base.rb:940:in `each'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/base.rb:940:in `each'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/base.rb:940:in `map'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/base.rb:940:in `collect_responses_from_templates'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/base.rb:925:in `collect_responses'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/base.rb:828:in `mail'
from /data/vhost/greece.alaveteli.org/alaveteli-2021-04-09T17-48-42/app/mailers/application_mailer.rb:31:in `mail_user'
from /data/vhost/greece.alaveteli.org/alaveteli-2021-04-09T17-48-42/app/mailers/request_mailer.rb:112:in `overdue_alert'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/abstract_controller/base.rb:194:in `process_action'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:132:in `run_callbacks'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/abstract_controller/callbacks.rb:41:in `process_action'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/abstract_controller/base.rb:134:in `process'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/rescuable.rb:25:in `block in process'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/rescuable.rb:24:in `process'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.5/lib/action_view/rendering.rb:32:in `process'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/base.rb:607:in `block in process'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/notifications.rb:168:in `block in instrument'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/notifications.rb:168:in `instrument'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/base.rb:606:in `process'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/message_delivery.rb:123:in `block in processed_mailer'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/message_delivery.rb:122:in `tap'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/message_delivery.rb:122:in `processed_mailer'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.5/lib/action_mailer/message_delivery.rb:113:in `deliver_now'
from /data/vhost/greece.alaveteli.org/alaveteli-2021-04-09T17-48-42/app/mailers/request_mailer.rb:327:in `block in alert_overdue_requests'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.5/lib/active_record/relation/delegation.rb:71:in `each'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.5/lib/active_record/relation/delegation.rb:71:in `each'
from /data/vhost/greece.alaveteli.org/alaveteli-2021-04-09T17-48-42/app/mailers/request_mailer.rb:288:in `alert_overdue_requests'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/commands/runner/runner_command.rb:41:in `<main>'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/commands/runner/runner_command.rb:41:in `eval'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/commands/runner/runner_command.rb:41:in `perform'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/command/base.rb:69:in `perform'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/command.rb:46:in `invoke'
from /data/vhost/greece.alaveteli.org/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/commands.rb:18:in `<top (required)>'
from bin/rails:4:in `require'
from bin/rails:4:in `<main>'
```

**Comment by gbp** [comment]
Fixed in transifex so will be resolved next time we deploy a hotfix.
